### ISSUE TITLE
not working in blender 3.2

### ISSUE THREAD

**Issue by LorenzWieseke** [takahirox/glTF-Blender-IO-materials-variants#18]
I have tried 0.0.2 and 0.0.3. Both work fine in blender 3.1

![image](https://user-images.githubusercontent.com/29607121/173009562-c8600015-e0e7-4e55-bed2-dc7aec72ba08.png)

In blender 3.2 they changed the gltf exporter again so the add-on doesn't add material variants anymore:

![image](https://user-images.githubusercontent.com/29607121/173009693-677ec596-0887-4986-ac7d-2c341841840f.png)
[Blender3.2.zip](https://github.com/takahirox/glTF-Blender-IO-materials-variants/files/8876563/Blender3.2.zip)

**Comment by LorenzWieseke** [comment]
gather_node_hook fails on <glTF-Blender-IO-materials-variants.glTF2ExportUserExtension object at 0x00000209B8A8E7D0>
get_material_cache_key() missing 1 required positional argument: 'export_settings'

**Comment by LorenzWieseke** [comment]
ok so it took me an hour but all I have to add was a 1 ;)

![image](https://user-images.githubusercontent.com/29607121/173796445-e81c5fbd-470c-4fc5-a775-3a94a8d0b849.png)

They changed their function calls again in the exporter ... (why not just leave it in as deprecated, so it won't crash ?)

The gltf2_blender_gather_materials.py / gather_material function now wants an active uv index that it passes to the get_material_cache_key function. That's the positional arg that's missing.

![image](https://user-images.githubusercontent.com/29607121/173796815-17ec0436-4119-4d71-830d-a0164e6c3f84.png)

**Comment by takahirox** [comment]
Thanks for the information. I will update the add-on hopefully soon.

**Comment by kongxiaojian123** [comment]
Blender 3.3 already has this plugin built in
![image](https://user-images.githubusercontent.com/8566872/189302994-8201c26c-9001-4f25-a59a-6e966ecc2f83.png)
![image](https://user-images.githubusercontent.com/8566872/189303092-c7f62067-5917-47ab-8a47-0dd10c687f00.png)
